feat: add Package.swift for SwiftPM support - WPB-10203 (#93)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -37,3 +37,40 @@ jobs:
       - name: 'Release new version'
         if: env.BRANCH_NAME == 'master'
         run: yarn version --minor
+
+  run-ios-spm-tests:
+    name: Test Swift package on macOS
+    runs-on: macos-15
+
+    steps:
+      - name: Install swift-protobuf
+        run: brew install swift-protobuf
+
+      - name: Check out repository
+        uses: actions/checkout@v3
+
+      - name: Ensure generated code is up-to-date
+        run: |
+          set -Eeuo pipefail
+          cd ios
+          ./update.sh
+
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "::error:: Working tree has uncommitted changes or untracked files:"
+            echo "Run ./update.sh in the ios directory and commit the changes!"
+            echo    # blank line for readability
+            git status --porcelain
+            exit 1             # any non-zero exit code fails the step → job
+          fi
+
+      - name: Run tests via swift test
+        run: swift test
+
+      - name: Run tests via xcodebuild
+        run: |
+          xcodebuild \
+            -workspace . \
+            -scheme GenericMessageProtocol \
+            -destination "platform=macOS,arch=arm64" \
+            -quiet \
+            clean test
